services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${CITY_API_DB_PWD:?error}
      - POSTGRES_USER=${CITY_API_DB_USER?:error}
      - POSTGRES_DB=city_api
    expose:
      - 5432
    #ports:
    #  - 5435:5432
    volumes:
      - /var/lib/postgres
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_city.sql
      - ./db/populate.sql:/docker-entrypoint-initdb.d/populate_city.sql
  postgres-test:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${CITY_API_DB_PWD:?error}
      - POSTGRES_USER=${CITY_API_DB_USER?:error}
      - POSTGRES_DB=city_api
    expose:
      - 5435
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_city.sql
      - ./db/populate.sql:/docker-entrypoint-initdb.d/populate_city.sql
  python:
    build:
      context: .
      dockerfile: python.dockerfile
    env_file:
      - .env
    depends_on:
      - postgres