services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${CITY_API_DB_PWD}
      - POSTGRES_USER=${CITY_API_DB_USER}
      - POSTGRES_DB=city_api
    ports:
      - "5435:5432"
    volumes:
      - /var/lib/postgres
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_city.sql
      - ./db/populate.sql:/docker-entrypoint-initdb.d/populate_city.sql
