services:
  db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${CITY_API_DB_PWD:?error}
      - POSTGRES_USER=${CITY_API_DB_USER?:error}
      - POSTGRES_DB=city_api
    ports:
      - ${CITY_API_DB_PORT?:error}:${CITY_API_DB_PORT?:error}
    volumes:
      - /var/lib/postgres
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_city.sql
      - ./db/populate.sql:/docker-entrypoint-initdb.d/populate_city.sql
    command: -p ${CITY_API_DB_PORT?:error}
  postgres-test:
    container_name: postgres-test
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${CITY_API_DB_PWD:?error}
      - POSTGRES_USER=${CITY_API_DB_USER?:error}
      - POSTGRES_DB=city_api
    ports:
      - ${CITY_API_TEST_DB_PORT?:error}:${CITY_API_TEST_DB_PORT?:error}
    command: -p ${CITY_API_TEST_DB_PORT?:error}
  python:
    container_name: flask-ci-cd
    build:
      context: .
      dockerfile: python.dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${CITY_API_PORT:?error}:${CITY_API_PORT:?error}
