{
 "title": "City API metrics dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request proportions",
   "type": "piechart",
   "description": "Proportion of requests depending on their method (get or post) and their status code.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total",
     "legendFormat": "Code: {{code}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Requests per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1h])",
     "legendFormat": "Code: {{code}}, method: {{method}}."
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "Scrape duration in seconds" }
   ]
  }
 ]
}